database:
  jdbc-driver: org.postgresql.Driver
  url: jdbc:postgresql://postgres.lab.viridian.cc:5432/viridian
  user: viridian
  password: sesamo
server:
  port: 8087

##### Custom properties ####
file.path: /home/isvar/Documents/statement/service-batch-converter/target/classes/Files/Statement_1998-01-01_2017-12-29.prn

